// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: authentication.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getAuthenticationByID = `-- name: GetAuthenticationByID :one
SELECT a.guid,
        a.id,
        a.user_guid,
        u.name as username,
        u.email as email,
        u.phone_number as phone_number,
        a.password,
        a.salt,
        a.status,
        a.fcm_token,
        a.forgot_password_token,
        a.forgot_password_expiry,
        a.created_at,
        a.created_by,
        a.updated_at,
        a.updated_by
FROM authentication_schema.authentication a
LEFT JOIN
    authentication_schema.user u ON a.user_guid = u.guid
WHERE a.guid = $1
    AND a.status != 'deleted'
LIMIT 1
`

type GetAuthenticationByIDRow struct {
	Guid                 string         `json:"guid"`
	ID                   sql.NullInt64  `json:"id"`
	UserGuid             sql.NullString `json:"user_guid"`
	Username             sql.NullString `json:"username"`
	Email                sql.NullString `json:"email"`
	PhoneNumber          sql.NullString `json:"phone_number"`
	Password             string         `json:"password"`
	Salt                 sql.NullString `json:"salt"`
	Status               string         `json:"status"`
	FcmToken             sql.NullString `json:"fcm_token"`
	ForgotPasswordToken  sql.NullString `json:"forgot_password_token"`
	ForgotPasswordExpiry sql.NullTime   `json:"forgot_password_expiry"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	CreatedBy            string         `json:"created_by"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	UpdatedBy            sql.NullString `json:"updated_by"`
}

func (q *Queries) GetAuthenticationByID(ctx context.Context, guid string) (GetAuthenticationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthenticationByID, guid)
	var i GetAuthenticationByIDRow
	err := row.Scan(
		&i.Guid,
		&i.ID,
		&i.UserGuid,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Password,
		&i.Salt,
		&i.Status,
		&i.FcmToken,
		&i.ForgotPasswordToken,
		&i.ForgotPasswordExpiry,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAuthenticationByUsername = `-- name: GetAuthenticationByUsername :one
SELECT a.guid,
        a.id,
        a.user_guid,
        u.name as username,
        u.email as email,
        u.phone_number as phone_number,
        a.password,
        a.salt,
        a.status,
        a.fcm_token,
        a.forgot_password_token,
        a.forgot_password_expiry,
        a.created_at,
        a.created_by,
        a.updated_at,
        a.updated_by
FROM authentication_schema.authentication a
LEFT JOIN
    authentication_schema.user u ON a.user_guid = u.guid
WHERE a.username = $1
    AND a.status != 'deleted'
LIMIT 1
`

type GetAuthenticationByUsernameRow struct {
	Guid                 string         `json:"guid"`
	ID                   sql.NullInt64  `json:"id"`
	UserGuid             sql.NullString `json:"user_guid"`
	Username             sql.NullString `json:"username"`
	Email                sql.NullString `json:"email"`
	PhoneNumber          sql.NullString `json:"phone_number"`
	Password             string         `json:"password"`
	Salt                 sql.NullString `json:"salt"`
	Status               string         `json:"status"`
	FcmToken             sql.NullString `json:"fcm_token"`
	ForgotPasswordToken  sql.NullString `json:"forgot_password_token"`
	ForgotPasswordExpiry sql.NullTime   `json:"forgot_password_expiry"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	CreatedBy            string         `json:"created_by"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	UpdatedBy            sql.NullString `json:"updated_by"`
}

func (q *Queries) GetAuthenticationByUsername(ctx context.Context, username string) (GetAuthenticationByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthenticationByUsername, username)
	var i GetAuthenticationByUsernameRow
	err := row.Scan(
		&i.Guid,
		&i.ID,
		&i.UserGuid,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Password,
		&i.Salt,
		&i.Status,
		&i.FcmToken,
		&i.ForgotPasswordToken,
		&i.ForgotPasswordExpiry,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAuthenticationIAMByID = `-- name: GetAuthenticationIAMByID :one
SELECT a.guid,
        a.id,
        a.user_guid,
        a.username      AS username,
        a.password,
        a.salt,
        a.status,
        u.email         AS email,
        u.phone_number  AS phone_number,
        a.fcm_token,
        a.forgot_password_token,
        a.forgot_password_expiry,
        a.created_at,
        a.created_by,
        a.updated_at,
        a.updated_by
FROM authentication_schema.authentication a
LEFT JOIN 
    authentication_schema.user u ON a.user_guid = u.guid
WHERE a.guid = $1
    AND a.status != 'deleted'
LIMIT 1
`

type GetAuthenticationIAMByIDRow struct {
	Guid                 string         `json:"guid"`
	ID                   sql.NullInt64  `json:"id"`
	UserGuid             sql.NullString `json:"user_guid"`
	Username             string         `json:"username"`
	Password             string         `json:"password"`
	Salt                 sql.NullString `json:"salt"`
	Status               string         `json:"status"`
	Email                sql.NullString `json:"email"`
	PhoneNumber          sql.NullString `json:"phone_number"`
	FcmToken             sql.NullString `json:"fcm_token"`
	ForgotPasswordToken  sql.NullString `json:"forgot_password_token"`
	ForgotPasswordExpiry sql.NullTime   `json:"forgot_password_expiry"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	CreatedBy            string         `json:"created_by"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	UpdatedBy            sql.NullString `json:"updated_by"`
}

func (q *Queries) GetAuthenticationIAMByID(ctx context.Context, guid string) (GetAuthenticationIAMByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthenticationIAMByID, guid)
	var i GetAuthenticationIAMByIDRow
	err := row.Scan(
		&i.Guid,
		&i.ID,
		&i.UserGuid,
		&i.Username,
		&i.Password,
		&i.Salt,
		&i.Status,
		&i.Email,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.ForgotPasswordToken,
		&i.ForgotPasswordExpiry,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertAuthentication = `-- name: InsertAuthentication :one
INSERT INTO authentication_schema.authentication(guid, user_guid, username, password, salt, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING authentication.guid, authentication.id, authentication.user_guid, authentication.username, authentication.password, authentication.salt, authentication.forgot_password_token, authentication.forgot_password_expiry, authentication.is_active, authentication.last_login, authentication.fcm_token, authentication.status, authentication.created_at, authentication.created_by, authentication.updated_at, authentication.updated_by
`

type InsertAuthenticationParams struct {
	Guid      string         `json:"guid"`
	UserGuid  sql.NullString `json:"user_guid"`
	Username  string         `json:"username"`
	Password  string         `json:"password"`
	Salt      sql.NullString `json:"salt"`
	Status    string         `json:"status"`
	CreatedBy string         `json:"created_by"`
}

func (q *Queries) InsertAuthentication(ctx context.Context, arg InsertAuthenticationParams) (AuthenticationSchemaAuthentication, error) {
	row := q.db.QueryRowContext(ctx, insertAuthentication,
		arg.Guid,
		arg.UserGuid,
		arg.Username,
		arg.Password,
		arg.Salt,
		arg.Status,
		arg.CreatedBy,
	)
	var i AuthenticationSchemaAuthentication
	err := row.Scan(
		&i.Guid,
		&i.ID,
		&i.UserGuid,
		&i.Username,
		&i.Password,
		&i.Salt,
		&i.ForgotPasswordToken,
		&i.ForgotPasswordExpiry,
		&i.IsActive,
		&i.LastLogin,
		&i.FcmToken,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const recordAuthenticationLastLogin = `-- name: RecordAuthenticationLastLogin :exec
UPDATE authentication_schema.authentication
SET last_login = (now() at time zone 'UTC')::TIMESTAMP
WHERE guid = $1
  AND status = 'active'
`

func (q *Queries) RecordAuthenticationLastLogin(ctx context.Context, guid string) error {
	_, err := q.db.ExecContext(ctx, recordAuthenticationLastLogin, guid)
	return err
}

const updateFCMToken = `-- name: UpdateFCMToken :exec
UPDATE authentication_schema.authentication
SET fcm_token = $1
WHERE guid = $2
  AND status = 'active'
`

type UpdateFCMTokenParams struct {
	FcmToken sql.NullString `json:"fcm_token"`
	Guid     string         `json:"guid"`
}

func (q *Queries) UpdateFCMToken(ctx context.Context, arg UpdateFCMTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateFCMToken, arg.FcmToken, arg.Guid)
	return err
}
