// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Barang struct {
	Guid       string         `json:"guid"`
	KodeBarang string         `json:"kode_barang"`
	NamaBarang string         `json:"nama_barang"`
	Kategori   string         `json:"kategori"`
	Deskripsi  sql.NullString `json:"deskripsi"`
	Harga      string         `json:"harga"`
	IsDeleted  bool           `json:"is_deleted"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Inventory struct {
	Guid      string         `json:"guid"`
	BarangID  string         `json:"barang_id"`
	Stok      int32          `json:"stok"`
	Lokasi    sql.NullString `json:"lokasi"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
