// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Barang struct {
	Guid       string         `json:"guid"`
	KodeBarang string         `json:"kode_barang"`
	NamaBarang string         `json:"nama_barang"`
	Kategori   string         `json:"kategori"`
	Deskripsi  sql.NullString `json:"deskripsi"`
	Harga      string         `json:"harga"`
	IsDeleted  bool           `json:"is_deleted"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Inventory struct {
	Guid       string         `json:"guid"`
	BarangID   string         `json:"barang_id"`
	Jumlah     int32          `json:"jumlah"`
	Keterangan sql.NullString `json:"keterangan"`
	Status     string         `json:"status"`
	IsDeleted  bool           `json:"is_deleted"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
