// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
)

const registerUser = `-- name: RegisterUser :one
INSERT INTO authentication_schema.user(
    guid, name, phone_number, email, address, created_at
)
VALUES (
    $1, $2, $3, $4, $5,
    (now() at time zone 'UTC')::TIMESTAMP
)
RETURNING guid, name, email, address, phone_number, created_at, updated_at
`

type RegisterUserParams struct {
	Guid        string         `json:"guid"`
	Name        string         `json:"name"`
	PhoneNumber string         `json:"phone_number"`
	Email       string         `json:"email"`
	Address     sql.NullString `json:"address"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (AuthenticationSchemaUser, error) {
	row := q.db.QueryRowContext(ctx, registerUser,
		arg.Guid,
		arg.Name,
		arg.PhoneNumber,
		arg.Email,
		arg.Address,
	)
	var i AuthenticationSchemaUser
	err := row.Scan(
		&i.Guid,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
